### ISSUE TITLE
New version 2.5

### ISSUE THREAD

**Issue by jbouzekri** [pslobo/docker-grok_exporter#1]
Hi,

Could you deploy a new version of your image with grok exporter 2.5 inside ?

Thanks

**Comment by pslobo** [comment]
Hey, sorry about the delayed but totally slipped through the cracks. New version has been pushed.

**Comment by jbouzekri** [comment]
Thanks, but I think you missed a reference to the version here : https://github.com/pslobo/docker-grok_exporter/blob/master/Dockerfile#L13

**Comment by pslobo** [comment]
Yeah, I caught that once the build failed.. Multi-tasking taking its toll. Fixed and pushed a new build.

**Comment by jbouzekri** [comment]
:+1:
